@devServer = https://localhost:7094
@listId = 1

@npToken= 0c874052d2b267bbe59a27810b9c3235

### https://localhost:7094

### Get lists
GET {{devServer}}/api/v1/todo-list/list
Accept: application/json

### Get list by id
GET {{devServer}}/api/v1/todo-list/{{listId}}
Accept: application/json

### Search GET 
###?TitleContains=title
###&IsCompleted=true
###&DescriptionContains=descr
###&Priorities=0
GET {{devServer}}/api/v1/todo-list/search/{{listId}}?IsCompleted=false
Accept: application/json

###
POST {{devServer}}/api/v1/todo-list/{{listId}}/add-item
Content-Type: application/json
Accept: application/json

{
  "title": "Додати авторизацію",
  "isCompleted": true,
  "description": "З використанням JWT токенів",
  "priority": 1
}

###

GET https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX



###

GET https://api.novaposhta.ua/v2.0/json
Content-Type: application/json

{
  "apiKey": "{{npToken}}",
  "modelName": "Address",
  "calledMethod": "getAreas",
  "methodProperties": {}
}




###
POST {{devServer}}/api/v1/auth/register
Content-Type: application/json

{
  "login": "user1@test.com",
  "password": "1111"
}

###
POST {{devServer}}/api/v1/auth/login
Content-Type: application/json

{
  "login": "user1@test.com",
  "password": "1111"
}


###
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMUB0ZXN0LmNvbSIsIm5hbWUiOiJ1c2VyMUB0ZXN0LmNvbSIsIm5hbWVpZCI6IjEiLCJqdGkiOiI3NDJjMGNkZS05MGYxLTQ1ODUtODBkZC1lMzM5MjAwNjlkMWQiLCJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwiZXhwIjoxNzY2MjY0MDM4fQ.toQHI41wn97eMQzjhKYM4kqnGCLnfKKs6P7chykxmKQ
###

GET {{devServer}}/api/v1/auth/profile
Accept: application/json
Authorization: Bearer {{token}}


